server:
  port: ${SERVER_PORT:7075}

spring:
  application:
    name: mall
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME:wlyykf_mall}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    database: ${REDIS_DATABASE}
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}  # Redis密码，如果没有密码则为空
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000
  mail:
    host: smtp.qq.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: false
          ssl.protocols: TLSv1.2

mybatis-plus:
  type-aliases-package: com.wlyykf.mall.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    org.mybatis: debug

admin:
  id: ${ADMIN_ID}

project:
  folder: ${PROJECT_FOLDER}